/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alerts/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать конфиг алерта
         * @description Создаёт конфигурацию spike-алерта для бренда
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Конфигурация алерта */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.CreateAlertConfigRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.AlertConfigResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/config/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить конфиг алерта
         * @description Возвращает конфигурацию алерта по ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID конфига */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.AlertConfigResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Обновить конфиг алерта
         * @description Обновляет параметры конфигурации алерта
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID конфига */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Обновляемые поля */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.UpdateAlertConfigRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.AlertConfigResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Удалить конфиг алерта
         * @description Удаляет конфигурацию алерта
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID конфига */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список брендов
         * @description Возвращает список всех брендов с пагинацией
         */
        get: {
            parameters: {
                query?: {
                    /** @description Лимит */
                    limit?: number;
                    /** @description Смещение */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedData"] & {
                                items?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.BrandResponse"][];
                            };
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Создать бренд
         * @description Создаёт новый бренд с ключевыми словами
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные бренда */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.CreateBrandRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.BrandResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить бренд
         * @description Возвращает бренд по ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID бренда */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.BrandResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Обновить бренд
         * @description Обновляет данные бренда
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID бренда */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Обновляемые поля */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.UpdateBrandRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.BrandResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Удалить бренд
         * @description Удаляет бренд по ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID бренда */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{id}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История алертов
         * @description Возвращает историю сработавших алертов для бренда
         */
        get: {
            parameters: {
                query?: {
                    /** @description Лимит */
                    limit?: number;
                    /** @description Смещение */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description UUID бренда */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedData"] & {
                                items?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.AlertResponse"][];
                            };
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{id}/alerts/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Конфиги алертов по бренду
         * @description Возвращает все конфигурации алертов для бренда
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID бренда */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.AlertConfigResponse"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список событий
         * @description Возвращает системные события с фильтром по типу
         */
        get: {
            parameters: {
                query?: {
                    /** @description Тип события */
                    type?: string;
                    /** @description Лимит */
                    limit?: number;
                    /** @description Смещение */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedData"] & {
                                items?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.EventResponse"][];
                            };
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Проверка здоровья
         * @description Возвращает статус приложения и его зависимостей
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.HealthResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список упоминаний
         * @description Возвращает упоминания с фильтрацией и пагинацией
         */
        get: {
            parameters: {
                query?: {
                    /** @description UUID бренда */
                    brand_id?: string;
                    /** @description UUID источника */
                    source_id?: string;
                    /** @description Статус (new, processing, processed, archived, discarded) */
                    status?: string;
                    /** @description ML-метка (negative, positive, neutral) */
                    label?: string;
                    /** @description Релевантность */
                    is_relevant?: boolean;
                    /** @description Поиск по тексту */
                    search?: string;
                    /** @description Дата от (RFC3339) */
                    date_from?: string;
                    /** @description Дата до (RFC3339) */
                    date_to?: string;
                    /** @description Лимит */
                    limit?: number;
                    /** @description Смещение */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedData"] & {
                                items?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.MentionResponse"][];
                            };
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mentions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить упоминание
         * @description Возвращает упоминание с ML-полями по ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID упоминания */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.MentionResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список источников
         * @description Возвращает список источников с пагинацией
         */
        get: {
            parameters: {
                query?: {
                    /** @description Фильтр по UUID бренда */
                    brand_id?: string;
                    /** @description Лимит */
                    limit?: number;
                    /** @description Смещение */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedData"] & {
                                items?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SourceResponse"][];
                            };
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Создать источник
         * @description Создаёт новый источник данных (telegram, web, rss)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные источника */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.CreateSourceRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SourceResponse"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить источник
         * @description Возвращает источник по ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID источника */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SourceResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Удалить источник
         * @description Удаляет источник по ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID источника */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Переключить статус источника
         * @description Переключает active/inactive статус источника
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID источника */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse"] & {
                            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.SourceResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "prod-pobeda-2026_internal_controller_http_v1_dto.AlertConfigResponse": {
            /** @example 0.5 */
            aggression?: number;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            brand_id?: string;
            /** @example 30 */
            cooldown_minutes?: number;
            /** @example 2024-01-01T12:00:00Z */
            created_at?: string;
            /** @example true */
            enabled?: boolean;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example negative */
            sentiment_filter?: string;
            /** @example 10 */
            threshold?: number;
            /** @example 2024-01-01T12:00:00Z */
            updated_at?: string;
            /** @example 60 */
            window_minutes?: number;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.AlertResponse": {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            brand_id?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            config_id?: string;
            /** @example 2024-01-01T12:00:00Z */
            created_at?: string;
            /** @example 2024-01-01T12:00:00Z */
            fired_at?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example 15 */
            mentions_count?: number;
            /** @example 2024-01-01T12:00:00Z */
            window_end?: string;
            /** @example 2024-01-01T11:00:00Z */
            window_start?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.BrandResponse": {
            /** @example 2024-01-01T12:00:00Z */
            created_at?: string;
            /**
             * @example [
             *       "apple pie",
             *       "apple fruit"
             *     ]
             */
            exclusions?: string[];
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /**
             * @example [
             *       "apple",
             *       "iphone",
             *       "macbook"
             *     ]
             */
            keywords?: string[];
            /** @example Apple */
            name?: string;
            /**
             * @example [
             *       "scandal",
             *       "leak",
             *       "bug"
             *     ]
             */
            risk_words?: string[];
            /** @example 2024-01-01T12:00:00Z */
            updated_at?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.CreateAlertConfigRequest": {
            /** @example 0.5 */
            aggression?: number;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            brand_id: string;
            /** @example 30 */
            cooldown_minutes: number;
            /** @example negative */
            sentiment_filter?: string;
            /** @example 10 */
            threshold: number;
            /** @example 60 */
            window_minutes: number;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.CreateBrandRequest": {
            /**
             * @example [
             *       "apple pie",
             *       "apple fruit"
             *     ]
             */
            exclusions?: string[];
            /**
             * @example [
             *       "apple",
             *       "iphone",
             *       "macbook"
             *     ]
             */
            keywords: string[];
            /** @example Apple */
            name: string;
            /**
             * @example [
             *       "scandal",
             *       "leak",
             *       "bug"
             *     ]
             */
            risk_words?: string[];
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.CreateSourceRequest": {
            /** @example {"chat":"@brand_news"} */
            config?: string;
            /** @example News channel */
            name: string;
            /**
             * @example telegram
             * @enum {string}
             */
            type: "web" | "rss" | "telegram";
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.ErrorDetail": {
            /** @example NOT_FOUND */
            code?: string;
            /** @example resource not found */
            message?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.ErrorResponse": {
            data?: unknown;
            error?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.ErrorDetail"];
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.EventResponse": {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example 2024-01-01T12:00:00Z */
            occurred_at?: string;
            /** @example {"brand_id":"550e8400-e29b-41d4-a716-446655440000","count":15} */
            payload?: string;
            /** @example spike_alert */
            type?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.HealthResponse": {
            /**
             * @example {
             *       "\"redis\"": "\"ok\"}",
             *       "{\"postgres\"": "\"ok\""
             *     }
             */
            dependencies?: {
                [key: string]: string;
            };
            /** @example ok */
            status?: string;
            /** @example 3600 */
            uptime_seconds?: number;
            /** @example 1.0.0 */
            version?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.MentionMLResponse": {
            /** @example true */
            is_relevant?: boolean;
            /** @example negative */
            label?: string;
            /** @example 0.87 */
            score?: number;
            /**
             * @example [
             *       "550e8400-e29b-41d4-a716-446655440000"
             *     ]
             */
            similar_ids?: string[];
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.MentionResponse": {
            /** @example @user */
            author?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            brand_id?: string;
            /** @example 2024-01-01T12:00:00Z */
            created_at?: string;
            /** @example false */
            deduplicated?: boolean;
            /** @example tg-12345 */
            external_id?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            ml?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.MentionMLResponse"];
            /** @example 2024-01-01T12:00:00Z */
            published_at?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            source_id?: string;
            /** @example new */
            status?: string;
            /** @example Текст публикации */
            text?: string;
            /** @example Заголовок */
            title?: string;
            /** @example 2024-01-01T12:00:00Z */
            updated_at?: string;
            /** @example https://t.me/channel/123 */
            url?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedData": {
            items?: unknown;
            /** @example 20 */
            limit?: number;
            /** @example 0 */
            offset?: number;
            /** @example 100 */
            total?: number;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedResponse": {
            data?: components["schemas"]["prod-pobeda-2026_internal_controller_http_v1_dto.PaginatedData"];
            /** @example null */
            error?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.SourceResponse": {
            /** @example {"chat":"@brand_news"} */
            config?: string;
            /** @example 2024-01-01T12:00:00Z */
            created_at?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @example News channel */
            name?: string;
            /** @example active */
            status?: string;
            /** @example telegram */
            type?: string;
            /** @example 2024-01-01T12:00:00Z */
            updated_at?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.SuccessResponse": {
            data?: unknown;
            /** @example null */
            error?: string;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.UpdateAlertConfigRequest": {
            /** @example 0.5 */
            aggression?: number;
            /** @example 30 */
            cooldown_minutes?: number;
            /** @example true */
            enabled?: boolean;
            /** @example negative */
            sentiment_filter?: string;
            /** @example 15 */
            threshold?: number;
            /** @example 60 */
            window_minutes?: number;
        };
        "prod-pobeda-2026_internal_controller_http_v1_dto.UpdateBrandRequest": {
            /**
             * @example [
             *       "apple pie"
             *     ]
             */
            exclusions?: string[];
            /**
             * @example [
             *       "apple",
             *       "iphone"
             *     ]
             */
            keywords?: string[];
            /** @example Apple Inc */
            name?: string;
            /**
             * @example [
             *       "scandal"
             *     ]
             */
            risk_words?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
